In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import shap as shap
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)

In [2]:
df = pd.read_excel('..\data\cleaned\creditcardmarketing_processed.xlsx')
display(df)

,# Bank Accounts Open,# Credit Cards Held,# Homes Owned,Household Size,Average Balance,Q1 Balance,Q2 Balance,Q3 Balance,Q4 Balance,Offer Accepted_Yes,Reward_Cash Back,Reward_Points,Mailer Type_Postcard,Income Level_Low,Income Level_Medium,Overdraft Protection_Yes,Credit Rating_Low,Credit Rating_Medium,Own Your Home_Yes,Offer Accepted_Yes.1
0,-0.541343,0.121081,-0.476084,0.449620,0.628724,1.223349,-0.267589,0.095704,0.343147,0,0,0,0,0,0,0,0,0,0,0
1,-0.541343,0.121081,1.864032,1.347164,-2.264609,-1.405430,-1.953241,-1.741902,-0.794628,0,0,0,0,0,1,0,0,1,1,0
2,1.575115,0.121081,-0.476084,-1.345469,-1.895627,-0.876449,-1.415407,-1.620841,-1.016458,0,0,0,1,0,0,0,0,1,1,0
3,1.575115,-1.133645,-0.476084,0.449620,0.795015,1.076589,1.662932,0.139070,-0.699813,0,0,0,0,0,1,0,0,0,0,0
4,-0.541343,0.121081,-0.476084,2.244709,0.772177,1.982953,0.781845,-0.108474,-0.796417,0,0,0,0,0,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,-0.541343,-1.133645,-0.476084,1.347164,-2.206799,-1.248993,-2.042881,-1.754551,-0.737382,0,1,0,0,0,0,0,1,0,1,0
17996,-0.541343,1.375807,-0.476084,-0.447925,-0.256976,0.118617,-0.129850,-0.178943,-0.492295,0,1,0,0,0,0,0,1,0,1,0
17997,-0.541343,0.121081,-0.476084,0.449620,0.418896,0.012175,-0.508084,0.231221,1.223312,0,1,0,0,0,0,0,1,0,0,0
17998,-0.541343,2.630533,1.864032,-1.345469,0.233335,-0.458747,-0.035839,-0.319880,1.439776,0,1,0,0,0,1,0,0,1,1,0
17999,1.575115,0.121081,-0.476084,-0.447925,0.329684,-1.040949,0.827758,1.691188,-0.370646,0,1,0,0,1,0,0,0,1,0,0

In [4]:
# Split the data into features (X) and target variable (y)
df.dropna(inplace=True)
df = df.drop('Offer Accepted_Yes.1', axis=1)
X = df.drop('Offer Accepted_Yes', axis=1) 
y = df['Offer Accepted_Yes']

# Get the feature names
feature_names = X.columns
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
model = LogisticRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

#print coefficients
coefficients = model.coef_[0]
feature_names = X.columns
feature_coefficients = dict(zip(feature_names, coefficients))
sorted_coefficients = sorted(feature_coefficients.items(), key=lambda x: np.abs(x[1]), reverse=True)
for feature, coefficient in sorted_coefficients:
    print(f"Feature: {feature}, Coefficient: {coefficient:.4f}")

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Feature: Credit Rating_Low, Coefficient: 1.7606
Feature: Income Level_Low, Coefficient: 0.9889
Feature: Mailer Type_Postcard, Coefficient: 0.9398
Feature: Credit Rating_Medium, Coefficient: 0.8522
Feature: Reward_Cash Back, Coefficient: -0.8280
Feature: Income Level_Medium, Coefficient: 0.3730
Feature: Reward_Points, Coefficient: -0.2172
Feature: Q1 Balance, Coefficient: -0.0984
Feature: Overdraft Protection_Yes, Coefficient: -0.0578
Feature: Household Size, Coefficient: -0.0566
Feature: Q3 Balance, Coefficient: 0.0446
Feature: # Credit Cards Held, Coefficient: -0.0351
Feature: Q2 Balance, Coefficient: 0.0288
Feature: Average Balance, Coefficient: -0.0244
Feature: # Homes Owned, Coefficient: 0.0203
Feature: Q4 Balance, Coefficient: -0.0196
Feature: Own Your Home_Yes, Coefficient: -0.0113
Feature: # Bank Accounts Open, Coefficient: -0.0086
Accuracy: 0.9468854282536151